### ISSUE TITLE
Foreign letters gets converted to ?

### ISSUE THREAD

**Issue by Agazoth** [KevinMarquette/PSGraph#83] opened 2018-12-07 19:06 UTC
When running Export-PSGraph on foreign letters they get converted to ?. Here is a test on the french ç and the danish ø:
```powershell
graph g { edge "François" "Sørensen" } | Export-PSGraph -ShowGraph
```
Everything is fine in the Powershell code.

```powershell
graph g { edge "François" "Sørensen" }
digraph g {
    compound="true";
    "François"->"Sørensen"
}
```

It is the creation of the image with dot.exe that introduces the error.
Line 187 in Export-PSGraph.ps1:

```powershell
$standardInput.ToString() | & $graphViz
```

This issue should probably be stated to the team creating graphViz.

**Comment by KevinMarquette** [comment] 2018-12-08 03:42
I did a little more testing on this. When I pipe in your sample graph, I get this output:

    digraph g {
        graph [bb="0,0,87.092,108",
                compound=true
        ];
        node [label="\N"];
        "Fran?ois"       [height=0.5,
                pos="43.546,90",
                width=1.1735];
        "S?rensen"       [height=0.5,
                pos="43.546,18",
                width=1.2096];
        "Fran?ois" -> "S?rensen"         [pos="e,43.546,36.104 43.546,71.697 43.546,63.983 43.546,54.712 43.546,46.112"];
    }

This confirms what you are seeing. My next test was to save our graph as a file and give that as a parameter to `$graphviz`

    & $graphviz c:\temp\graph.dot

    digraph g {
        graph [bb="0,0,88.392,108",
                compound=true
        ];
        node [label="\N"];
        Franτois         [height=0.5,
                pos="44.196,90",
                width=1.1735];
        S°rensen         [height=0.5,
                pos="44.196,18",
                width=1.2277];
        Franτois -> S°rensen     [pos="e,44.196,36.104 44.196,71.697 44.196,63.983 44.196,54.712 44.196,46.112"];
    }

I don't get the `?` this time, but these characters are still not correct.

**Comment by KevinMarquette** [comment] 2018-12-08 04:03
I started trying to reproduce these results with PowerShell 6.1. From the console, this output also looks wrong:

    $graph | & $graphViz
    digraph g {
            graph [bb="0,0,88.392,108",
                    compound=true
            ];
            node [label="\N"];
            Fran├ºois        [height=0.5,
                    pos="44.196,90",
                    width=1.1735];
            S├╕rensen        [height=0.5,
                    pos="44.196,18",
                    width=1.2277];
            Fran├ºois -> S├╕rensen   [pos="e,44.196,36.104 44.196,71.697 44.196,63.983 44.196,54.712 44.196,46.112"];
    }

But if I actually generate a graph it will show the correct characters. It looks like this is solved in PowerShell 6.1. So this is a bug with Windows Powershell and the way it pipes to executables.

Still trying to chase down why saving to a file first is not working like I would expect. So I am playing with file encodings.

**Comment by KevinMarquette** [comment] 2018-12-08 04:12
I was able to get it to work from a file if I saved it this way:

    $graph  | Set-Content c:\temp\graph.dot -Encoding utf8NoBOM

But that encoding option is not available on Windows PowerShell 5.1

I hate to close the issue this way but I don't have an easy way to fix this on my end. It's resolved by updating PowerShell to the current version (PS 6.1).

**Closed by KevinMarquette** 2018-12-08 04:12 UTC

**Comment by Agazoth** [comment] 2018-12-08 05:57
The digraph I get when running the  initail command is a lot different from yours. 

I installed PSGraph in Powershell 6.1 - had to AllowClubber since node has a twin in PSDesiredStateConfiguration. In both Windows Powershell 5.1 and Powershell 6.1 I get this result:

```powershell
PS C:\>graph g { edge "François" "Sørensen" }
digraph g {
    compound="true";
    "François"->"Sørensen"
}
```

No hight, position and width at all.

But in Powershell 6.1 there is a huge difference in the output. If I go:

```powershell
graph g { edge "François" "Sørensen" } | Export-PSGraph -ShowGraph
```

The names show up with ? in strad of the european characters in Windows Powershell 5.1:
![Not Working](https://imageshack.com/a/img921/948/1aIlo9.png)

But in Powershell 6.1 the image includes the correct european characters.

![Working](https://imageshack.com/a/img922/9766/qdNdwR.png)

**Comment by KevinMarquette** [comment] 2018-12-08 06:56
My outputs is actually the output of dot.exe after passing it that simple digraph from your example. That is where the height and position info comes from. It's the default standard out when no image is specified. 

I figured it was best to bypass Export-PSGraph while troubleshooting this one. I was unable to find a viable workaround in PowerShell 5.1 in my testing.
